[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dice-game"
version = "0.4.1"
description = "A simple CLI dice game"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }

authors = [
    { name = "Dennis Major" }
]

dependencies = [
    "argon2-cffi>=23.1.0"
]

keywords = ["game", "dice", "cli"]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: MIT License",
    "Environment :: Console"
]

[project.scripts]
dicegame = "dicegame.__main__:main"
